http:
  protocol: http
  host: www.httpbin.org
  port: 80
  rfc_name: rfc9110
  trans_layer: tcp
  
lightftp:
  protocol: ftp
  host: 127.0.0.1
  port: 2200
  rfc_name: rfc959
  trans_layer: tcp

pureftpd:
  protocol: ftp
  host: 127.0.0.1
  port: 2121
  rfc_name: rfc959
  trans_layer: tcp

kamailio:
  protocol: sip
  host: 127.0.0.1
  port: 5060
  rfc_name: rfc3261
  trans_layer: udp

llm:
  base_url: https://xiaoai.plus/v1
  api_key: sk-JkrKujmSQfYTAkmSJesJJiM88GkuYz5InmL3rdaObbGP4gRS
  model: gpt-4-turbo
  async_sem: 8