libcoap:
  protocol: coap
  host: 127.0.0.1
  port: 5683
  rfc_name: ["rfc7252", "rfc7641", "rfc7390", "rfc7641", "rfc7959", "rfc7967", "rfc8132", "rfc8323", "rfc8516", "rfc8613", "rfc8768", "rfc8974", "rfc9175", "rfc9177"]
  trans_layer: udp
  server: parent

tinydtls:
  protocol: dtls
  host: 127.0.0.1
  port: 20220
  rfc_name: ["rfc6347"]
  trans_layer: udp
  server: parent

lightftp:
  protocol: ftp
  host: 127.0.0.1
  port: 2200
  rfc_name: ["rfc959","rfc2428","rfc3659","rfc2389","rfc2228"]
  trans_layer: tcp
  server: parent

ftp:
  protocol: ftp
  host: 127.0.0.1
  port: 8021
  rfc_name: ["rfc959","rfc2428","rfc3659","rfc2389","rfc2228"]
  trans_layer: tcp
  server: parent

FTP:
  protocol: ftp
  host: 127.0.0.1
  port: 8487
  rfc_name: ["rfc959","rfc2428","rfc3659","rfc2389","rfc2228"]
  trans_layer: tcp
  server: parent

forked-daapd:
  protocol: daapd
  host: 127.0.0.1
  port: 3689
  rfc_name: ["rfc7230","rfc7231","rfc7232","rfc7233","rfc7234","rfc7235"]
  trans_layer: tcp
  server: parent

bftpd:
  protocol: ftp
  host: 127.0.0.1
  port: 21
  rfc_name: ["rfc959","rfc2428","rfc3659","rfc2389","rfc2228"]
  trans_layer: tcp
  server: parent

pureftpd:
  protocol: ftp
  host: 127.0.0.1
  port: 21
  rfc_name: ["rfc959","rfc2428","rfc3659","rfc2389","rfc2228"]
  trans_layer: tcp
  server: parent

exim:
  protocol: smtp
  host: 127.0.0.1
  port: 25
  rfc_name: ["rfc5321"]
  trans_layer: tcp
  server: parent

kamailio:
  protocol: sip
  host: 127.0.0.1
  port: 5060
  rfc_name: ["rfc3262", "rfc3261",  "rfc3311", "rfc3428", "rfc3515", "rfc3903", "rfc6086", "rfc6665"]
  trans_layer: udp
  server: parent

live555:
  protocol: rtsp
  host: 127.0.0.1
  port: 8554
  rfc_name: ["rfc7826"]
  trans_layer: tcp
  server: parent

lighttpd:
  protocol: http
  host: 127.0.0.1
  port: 8080
  rfc_name: ["rfc9110","rfc7540","rfc2616","rfc1945"]
  trans_layer: tcp
  server: child

dnsmasq:
  protocol: dns
  host: 127.0.0.1
  port: 5353
  rfc_name: ["rfc1034", "rfc1035"]
  trans_layer: udp
  server: parent

llm:
  base_url: https://xiaoai.plus/v1
  api_key: sk-vUIK7aS2md6wOsKyEsEEDzzDYNu5BwwaQ9UofpG9N7XB6egQ
  model: gpt-5-mini-2025-08-07
  async_sem: 8